### ISSUE TITLE
Adding Category

### ISSUE THREAD

**Issue by yavuzkoca** [PHPJuice/slopeone#3]
How can I add category to items? Lets say I have some movies such as;
```
$data =[
  [
    "lord of the rings" => 1,
    "harry potter" => 0.5,
    "titanic" => 0.2
  ],
  [
    "lord of the rings" => 1,
    "harry potter" => 0.5,
    "titanic" => 0.2
  ],
  [
    "lord of the rings" => 1,
    "harry potter" => 0.5,
    "titanic" => 0.2
  ]
];
```
But I want to add category for these movies also such as;
```
$data =[
  [
    "lord of the rings" => [
    "category" => ["action", "fantastic"],
    1
    ],
    "harry potter" => [
    "category" => ["fantastic"],
    0.5
    ],
    "titanic" => 0.2
  ],
  [
    "lord of the rings" => 1,
    "harry potter" => 0.5,
    "titanic" => 0.2
  ]
];
```
And I want to predict movies by category selection or not. How can I do that, I hope it is clear. Thanks in advance

**Comment by mhdcodes** [comment]
this algorithm works with a pure matrix of items => values
you can add categories to your $data then run a map function and grab only the items and their values I will soon push a demo repository to showcase a real-life example from with the movieslens dataset

**Comment by mhdcodes** [comment]
# DEMO

## Get JSON file that includes ratings
 [Movies Ratings](https://jsoneditoronline.org/?id=41765be6ba8538d079fe1abd4fc2926d)

### First Step is to decode the file
```PHP
$ratingsFile = file_get_contents("../database/ratings.json");
$ratings = json_decode($ratingsFile, true);
```
### initiate the algorithm
```PHP
$slopeone = new \App\Slopeone();
```
### Loop through the data and build our input matrix

```PHP
$i = 0;
for ($i=0; $i < 20; $i++) {
	$ratingData = [];
	foreach ($ratings[$i]['ratings'] as $rating) {
		$ratingData[$rating['movieTitle']] = $rating['rating'];
	}
	$slopeone->add($ratingData);
}
```

### Predicting results for new User who rated Batman v Superman
```PHP
$results = $slopeone->predict([
  "Batman v Superman(2016)" => 2,
 ]);
```

**Comment by yavuzkoca** [comment]
Thanks for reply and for the demo. It helped for movie recommendation but you haven't give an example of how to add category for these movies. I just don't want to see movies that who gave rating '2' for 'Batman V Superman'. Also I want to see, lets say action movies.

Thanks in advance

**Comment by mhdcodes** [comment]
I think this is beyond the scope of this algorithm, this slope-one implementation is just a prediction method that works with set's  Item => ratings
in order to do what you are looking for you should use a full-featured recommendation engine or make your own. based on the recommendations given by this algorithm you can fetch all the movies from the category of the predicted items.
Let's say "Batman v Superman" is of the category action, you can do a query to select all action movies.
